import { randomUUID } from "crypto";

export const panelsMock = [
  {
    title: "Lorem ipsum",
    description: "Lorem ipsum dolor sit amet",
    slug: randomUUID(),
    owner: randomUUID(),
    createdAt: new Date(),
    updatedAt: new Date(),
    password: "12345678",
    clientPassword: "12345678",
    status: "ACTIVE",
  },
  {
    title: "Lorem ipsum",
    description: "Lorem ipsum dolor sit amet",
    slug: randomUUID(),
    owner: randomUUID(),
    createdAt: new Date(),
    updatedAt: new Date(),
    password: "12345678",
    clientPassword: "12345678",
    status: "ACTIVE",
  },
  {
    title: "Lorem ipsum",
    description: "Lorem ipsum dolor sit amet",
    slug: randomUUID(),
    owner: randomUUID(),
    createdAt: new Date(),
    updatedAt: new Date(),
    password: "12345678",
    clientPassword: "12345678",
    status: "ACTIVE",
  },
  {
    title: "Lorem ipsum",
    description: "Lorem ipsum dolor sit amet",
    slug: randomUUID(),
    owner: randomUUID(),
    createdAt: new Date(),
    updatedAt: new Date(),
    password: "12345678",
    clientPassword: "12345678",
    status: "ACTIVE",
  },
  {
    title: "Lorem ipsum",
    description: "Lorem ipsum dolor sit amet",
    slug: randomUUID(),
    owner: randomUUID(),
    createdAt: new Date(),
    updatedAt: new Date(),
    password: "12345678",
    clientPassword: "12345678",
    status: "ACTIVE",
  },
];
